spring:
  application:
    name: spring-boot-kafka-protobuf-playground

playground:
  kafka:
    topic: playground.queue
    dlt-topic: playground.queue.DLT
    share-group: playground.queue.workers
    listener-auto-startup: true
